services:
  ethglobal-frontend-service:
    profiles: [stage]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ethglobal_frontend
    environment:
     - NGINX_HOST=ethglobal.envelop.is
     - NGINX_PORT=8081
     - APP_URL=/swapper
    labels:
      - traefik.enable=true
      - traefik.http.routers.ethglobal_frontend.rule=Host(`ethglobal.envelop.is`)  && Path(`/swapper`)
      - traefik.http.routers.ethglobal_frontend.entrypoints=websecure
      - traefik.http.routers.ethglobal_frontend.tls.certresolver=leresolver
      - traefik.http.routers.ethglobal_frontend.tls=true
      #- traefik.http.routers.ethglobal_frontend.middlewares=to-http
      - traefik.http.services.ethglobal_frontend-service.loadbalancer.server.port=8081
      #- traefik.http.middlewares.to-http.redirectscheme.scheme=http
    restart: always

  ethglobal-frontend-local:
    profiles: [local]
    build:
      context: .
      dockerfile: Dockerfile
    #image: nginx
    container_name:  ethglobal-frontend_local
    # volumes:
    #  - ./nginx:/etc/nginx/templates
    #  - ./build:/usr/share/nginx/html/app
    ports:
     - 8080:8081
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=8081
     - APP_URL=/swapper
    command: [nginx-debug, '-g', 'daemon off;']
